### ISSUE TITLE
Word Wrapping on mobile

### ISSUE THREAD

**Issue by magnessjo** [UMD-Digital/elements-accordion#1]
Example 
![image0](https://user-images.githubusercontent.com/856595/221918641-8cf2e62f-af67-4b0d-a43a-e869d934643c.png)

**Comment by brionwolf** [comment]
_Just_ noticed this, if it helps having a test case, I had this issue on the microsites, and just overwrote your styles:

```css
umd-accordion:defined [data-accordion='button'] span {
  line-height: 1.3em !important;
  white-space: normal !important;
}
```

example: https://micros-sites-production.cl-umd-edu-1.servd.dev/components/example-accordions

No issues found.
